srv/applications/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

srv/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

#from rest_framework_extensions.routers import DefaultRouter
from rest_framework_extensions.routers import (
    ExtendedSimpleRouter as SimpleRouter
)

from srv.applications.users.views import UserViewSet
from srv.applications.authentication.views import AuthenticationViewSet
from srv.applications.game.views import *
from srv.applications.game import urls as gameurls
from srv.applications.profiles import urls as profileurls

#import  srv.applications.symbolic_math

#from .settings import MEDIA_ROOT

api_router = SimpleRouter()
api_router.register(r'users',                UserViewSet)
api_router.register(r'auth',                 AuthenticationViewSet)
api_router.register(r'categories',           CategoryViewSet)
api_router.register(r'categories-with-apps', CategoryAppsViewSet)
api_router.register(r'apps',                 AppViewSet)
api_router.register(r'apps-minimal',         AppMinimalViewSet)
api_router.register(r'instances',            InstanceViewSet)
api_router.register(r'snapshots',            SnapshotViewSet)
api_router.register(r'code_modules',         CodeModuleViewSet)
api_router.register(r'instances-ordered',    OrderedInstancesViewSet)


urlpatterns = [
    url(r'^api/', include(api_router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^game/', include(gameurls, namespace='game')),
    url(r'^profiles/', include(profileurls, namespace='profiles')),
    url(r'^symbolic_math/', include('srv.applications.symbolic_math.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

srv/applications/game/models.py
from __future__ import unicode_literals

import os
import os.path
import json
import itertools
import random
import copy

#from authtools.models import User
from srv.applications.users.models import User

from django.http import HttpResponse, JsonResponse
from django.db import models
from django.conf import settings
from django_thumbs.db.models import ImageWithThumbsField

#from django.contrib.postgres.fields import JSONField
#from jsonfield import JSONField
#from jsonfield import JSONField

# that daggum jsonfield... come awn, now, really?  so many!
#  ---> CONCLUDE: eventually must go to CouchDB

# mr codeswitcher is a flip-of-the-lip syntactic dick

from srv.settings import MEDIA_URL, MEDIA_ROOT
from sets import Set

from srv.applications.symbolic_math.views import *

DIALECTS = (
    ('javascript', 'text/javascript'),
    ('coffeescript', 'text/coffeescript'),
    ('paperscript', 'text/paperscript'),
)

class TimestamperMixin(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Category(models.Model):
    name = models.CharField(max_length=1000)
    parent = models.ForeignKey('self', null=True, blank=True, related_name="children")
    description = models.TextField(null=True, blank=True)
    image = ImageWithThumbsField(null=True, blank=True, sizes=((125,125),(200,200),(300,300)))
    enabled = models.BooleanField(null=False, blank=False, default=True)
    popularity = models.IntegerField(default=1)

    def __unicode__(self):
        return self.name

    def get_total_popularity(self):
        return sum(map(lambda app: app.popularity, self.apps.all()))

    def get_avg_popularity(self):
        return sum(map(lambda app: app.popularity, self.apps.all())) / self.apps.count()


class JSLibrary(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    scriptPath = models.CharField(max_length=200, blank=False, null=False)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "JS libraries"

class SavedFunction(TimestamperMixin, models.Model):
    """
    snippet-like, meant for short user functions
    """
    owner = models.ForeignKey(User, related_name='savedFunctions')
    title = models.CharField(max_length=255, null=True, blank=True)
    language = models.CharField(max_length=20,
        choices=DIALECTS, default="javascript")
    source = models.TextField(null=False, blank=False)

    def __unicode__(self):
        return self.title + ": " + self.source[:50] + "..."

class CodeModule(TimestamperMixin, models.Model):
    """
    for larger system-provided blocks that
    hould be available to every user
    """
    title = models.CharField(max_length=255, null=True, blank=True)
    language = models.CharField(max_length=20, choices=DIALECTS, default="javascript")
    source = models.TextField(null=False, blank=False)

    def __unicode__(self):
        return self.title + ": " + self.source[:50] + "..."


class ZeroPlayerGame(TimestamperMixin, models.Model):

    parent = models.ForeignKey('self', null=True, blank=True, related_name="children")
    category = models.ForeignKey(Category, related_name="apps")
    owner = models.ForeignKey(User)
    title = models.CharField(max_length=500)
    subtitle = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField(blank=True)
    scriptType = models.CharField(max_length=100, null=True, blank=False)
    source = models.TextField(blank=True)
    seedStructure = models.TextField(blank=True)
    extraIncludes = models.ManyToManyField('JSLibrary', blank=True)
    mainImage = models.CharField(null=True, blank=True, max_length=255)
    required_modules = models.ManyToManyField('CodeModule', blank=True)
    popularity = models.IntegerField(default=1)

    def __unicode__(self):
        return "\"%s\", by %s" % (self.title, self.owner.name)

    def simplify_seed(self, seed):
        return { k:v['value'] for k,v in seed.iteritems() }

    @staticmethod
    def simplify_seed(seed):
        return { k:v['value'] for k,v in seed.iteritems() }

    def getDefaultSeed(self):
        seedDict = json.loads(self.seedStructure)
        seed = {}
        # ensure seedDict has `type` and `default` on each value-dict
        for k,v in seedDict.iteritems():
            if 'type' not in v:
                v['type'] = 'string'


            value = v['value'] if 'value' in v else v['default']
            seed[k] = {'type':v['type'], 'value':value}

        return seed

    def getSeedVector(self, seed={}):
        seedDict = json.loads(self.seedStructure)

        # ensure seedDict has `type` and `default` on each value-dict
        for k,v in seedDict.iteritems():
            if 'type' not in v:
                v['type'] = 'string'
            if 'default' not in v:
                if v['type'] == 'number':
                    v['value'] = 0
                else:
                    v['value'] = ''

            value = seed[k]['value'] if 'value' in seed[k] else v['default']
            seed[k] = {'type':v['type'], 'value':value}

        vector = copy.deepcopy(seed) #{ k:v for k,v in seed.iteritems() }
        for k,v in vector.iteritems():
            if type(v) is not dict:
                v = {'value':v, 'type':'string'}

            if v['type'] == 'math':
                _val = v['value']
                expr = SymbolicExpression(_val)
                sym = expr.latex(raw=True)
                v.update(sym)
            elif v['type'] == 'number':
                try:
                    v['value'] = int(v['value'])
                except Exception:
                    pass
            elif v['type'] == 'color':
                try:
                    v['value'] = int(str(v['value']).replace('#', ''), 16)
                except Exception:
                    raise Exception

        # print "==== getSeedVector ===="
        # print vector

        return vector

    def instantiate(self, request, seed={}):
        """
        Now should be the *only place to handle:
            - seed creation
            - kv col management
        does not need to be server-side anymore... which is easier?
        """
        if request.user is None:
            raise Exception("Must be logged in.")

        if seed == {}:
            print '--default seed'
            seed = self.getDefaultSeed()
            print seed


        vector = self.getSeedVector(seed)
        print '--seed', seed
        print '--vector', vector
        # create dict
        inst = {
            'game': self,
            'instantiator': self.owner,
            'seed': json.dumps(seed),
            'vector': json.dumps(vector)
        }
        #print '---inst', inst

        # create the new instance
        #print "searching gi's for vector: " + inst['vector']
        isNew = False
        try:
            instance = GameInstance.objects.get(vector=inst['vector'])
        except GameInstance.DoesNotExist:
            instance = GameInstance.objects.create(**inst)
            isNew = True

        meta = {}

        if isNew:
            meta['alreadyExists'] = False
        else:
            meta['alreadyExists'] = True
            return meta, instance

        instance.parseVectorParams()
        instance.save()

        return meta, instance

    def getImageSet(self, order=20, shuffled=False):
        images = map(lambda obj: obj.image.name.replace("./", ""), list(itertools.chain(
                    *map(lambda l: l.all(),
                        [instance.images for instance in self.instances.all()]))
                    )
                )
        if shuffled:
            random.shuffle(images)
        return images[:order]



class GameInstance(TimestamperMixin, models.Model):

    game = models.ForeignKey(ZeroPlayerGame, related_name='instances')
    instantiator = models.ForeignKey(User)
    seed = models.TextField()
    popularity = models.IntegerField(default=1)
    vector = models.CharField(max_length=5000, null=True, blank=False, unique=True)

    def __unicode__(self):
        return "%s's instance of \"%s\", by %s" % (self.instantiator.name, self.game.title, self.game.owner.name)

    # def save(self, *args, **kwargs):
    #     print '--save instance'
    #     kvs, kdict = self.parseVectorParams()
    #     print kdict
    #     print '--inserted vector-string', json.dumps(kdict)
    #     kwargs.update({'vector',json.dumps(kdict)})
    #     print instance
    #     super(GameInstance).save(*args, **kwargs)

    def getSeedVector(self):
        seed = json.loads(self.seed)
        return self.game.getSeedVector(seed)

    def parseVectorParams(self):
        print "============="
        print 'parseVectorParams'
        seed = json.loads(self.seed)
        seedDict = json.loads(self.game.seedStructure)
        for kv in self.vectorparams.all():
            kv.delete()

        kvs = []
        kdict = {}
        for k,v in seed.iteritems():

            if 'type' not in seedDict[k]:
                seedDict[k]['type'] = 'string'

            paramdict = {
                'key':k,
                'instance':self,
                'app':self.game,
                'val':v['value'],
                'jsonval':json.dumps(v),
                'valtype':seedDict[k]['type'],
                'ordering':0
            }

            if seedDict[k]['type'] == 'number':
                paramdict['int_val'] = int(paramdict['val'])
            elif seedDict[k]['type'] == 'color':
                paramdict['int_val'] = int(paramdict['val'].replace('#',''), 16)


            kvs.append(SeedVectorParam(**paramdict))
            kdict[k] = paramdict

        for i,kv in enumerate(kvs):
            kv.ordering = i
            kv.save()
            self.vectorparams.add(kv)

        self.save()
        print '---parseVectorParams', kdict
        return kvs, kdict

    @staticmethod

www/templates/views/app-display.html
<!-- <md-content ng-init="initialize()" scroll-to-top> -->

<!-- loading spinner -->
<!-- <div ng-if="ctrl.loading" class="loading-bg-base">
        <div class="loader-lg">
            <svg class="circular2">
            <circle class="path" cx="125" cy="125" r="40" fill="none" stroke-width="4"
                stroke-miterlimit="10"/>
            </svg>
            <div class="loading-text">Loading...</span></div>
        </div>
    </div> -->




<h3 class="section-title">{{ ctrl.app.title }}</h3>

<div layout="row">
    <div flex="grow" ng-cloak>
        <div><strong>Author:</strong> {{ctrl.app.owner.name}}</div>
        <div><strong>Category:</strong> {{ctrl.app.category}}</div>
        <div class="text-muted">created @ {{ ctrl.app.created }}</div>
    </div>
    <div flex="none">
        <md-button class="md-raised md-accent" ng-click="ctrl.selectFirstInstance()" role="button" layout-align="center center">
            <md-icon md-svg-src="/assets/img/icons/ic_play_circle_outline_black_24px.svg">play_circle_outline</md-icon>
            <span>Instantiate App</span>
        </md-button>
    </div>
</div>

<md-divider class="big-divide"></md-divider>

<div ng-if="userLoggedIn" layout="row">
    <md-button class="md-raised md-primary" ui-sref="app.edit({id:ctrl.app.id})" role="button" layout-align="center center">
        <md-icon md-font-set="material-icons">&#xE254;</md-icon>
        <span>Edit</span>
    </md-button>

    <md-button class="md-raised md-warn" href="#/apps/{{ ctrl.app.id }}/edit/" role="button" layout-align="center center" ng-click="delete()">
        <md-icon md-font-set="material-icons">&#xE872;</md-icon>
        <span>Delete</span>
    </md-button>
</div>

<div class="spacer"></div>

<div class="caption">
    <p ng-repeat="paragraph in ctrl.app.description|splitLines track by $index">{{ paragraph }}</p>
</div>

<p hide-gt-xs></p>

<!-- <div class="image-grid float-right" hide-xs>
                <md-grid-list md-cols="3" md-row-height="1:1" md-gutter="2px">
                    <md-grid-tile ng-repeat="im in ctrl.app.images | limit:9">
                        <img src="/media/{{ im | thumbnail:125 }}" style="max-width:100%; height:auto; border:1px solid #ddd;" />
                    </md-grid-tile>
                </md-grid-list>
            </div> -->

<!-- <div flex="5"></div>
            <div flex="none">

                <div style="width:300px; float: right;" ng-if="images.length > 0">
                    <md-grid-list md-cols="3"
                        md-row-height="100px" md-gutter="0px">
                        <md-grid-tile ng-repeat="image in images | limit:9">
                            <img ng-src="/media/{{ image | thumbnail:125 }}"
                                class="thumbnail thumbnail-med" width="100" height="100" />
                        </md-grid-tile>
                    </md-grid-list>
                </div>

            </div> -->


<md-content layout="column">

    <h3>Instances</h3>

    <md-progress-linear md-mode="indeterminate" ng-disabled="!ctrl.loadingInstances"></md-progress-linear>

    <div layout="row" layout-wrap>
        <!-- infinite-scroll="ctrl.instanceFactory.next()"
                    infinite-scroll-distance="1"> -->

        <div ng-repeat="instance in ctrl.instances track by $index" class="no-padding" flex="nogrow">
            <!-- class="col-xs-3 col-sm-3 col-md-2 col-lg-2 no-padding" -->

            <md-card ui-sref="app.instance({app: ctrl.app.id, id:instance.id})">
                <md-card-content class="no-padding overlay-bg">

                    <div class="overlay-item">
                        <seed-list ng-model="instance._seed"></seed-list>
                    </div>

                    <img ng-if="instance.images.length > 0" bn-lazy-src="/media/{{ instance.image | thumbnail:125 }}" class="thumbnail thumbnail-lg nomargin" />


                </md-card-content>
                <md-card-actions ng-if="userLoggedIn" class="no-margin text-smaller">

                    <md-button class="md-small pull-right" ng-click="ctrl.deleteInstance($event, instance)" data-id="{{instance.id}}" role="button">
                        Delete
                    </md-button>
                </md-card-actions>

            </md-card>

        </div>

    </div>

</md-content>


<div ng-if="ctrl.app.instances.length == 0">
    <md-button class="md-raised md-primary" ng-click="ctrl.instantiate()" role="button" layout-align="center center">
        <md-icon md-font-set="material-icons">add_circle</md-icon>
        <span>Create first instance</span>
    </md-button>
</div>





<!-- </md-content> -->

www/templates/views/app-editor.html
<md-content ng-cloak ng-init="initializeEditor()">

  <!-- <div ng-if="isLoading" class="loading-bg">
      <div class="loader">
        <svg class="circular">
          <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2"
              stroke-miterlimit="10"/>
        </svg>
      </div>
      <div class="loading-text">Loading...</span></div>
  </div> -->



  <md-card>
    <md-card-content>

    <form name="appform">

      <md-content class="container-fluid fill-vertical" layout="row" layout-padding>
        <div flex="35" layout="column" layout-align="top down">

          <md-input-container>
            <label for="id_title">Title</label>
            <input type="text" id="id_title" placeholder="Title" ng-model="app.title" />
          </md-input-container>
          <md-input-container>
            <label for="id_title">Sub-title</label>
            <input type="text" id="id_subtitle" placeholder="Sub-title" ng-model="app.subtitle" />
          </md-input-container>
          <md-input-container>
              <label>Category</label>
              <md-select ng-model="app.category">
                <md-option ng-repeat="category in categories"
                  ng-value="category.name"
                  ng-selected="(category.name == app.category) ? true:false">{{category.name}}</md-option>
              </md-select>
            </md-input-container><br />
            <md-input-container>
              <label>Script Language</label>
              <md-select ng-model="app.scriptType">
                <md-option ng-repeat="st in scriptTypes" ng-value="st">{{st}}</md-option>
              </md-select>
            </md-input-container><br />
          <md-input-container>
            <label class="control-label">Description</label>

              <textarea type="text" id="id_description"
                ng-model="app.description"></textarea>

          </md-input-container>
          <!-- <md-input-container>
            <label class="control-label">Code Modules</label>
                <br /><br /><br />

                <md-checkbox ng-repeat="mod in codeModules"
                  ng-model="mod.selected" flex>{{ mod.title }}</md-checkbox>


          </md-input-container> -->

        </div>
        <div flex="grow" layout="column">

            <md-tabs md-dynamic-height md-border-bottom>
              <md-tab label="Source Code">

                  <md-content>
                   <!--  <div ng-if="isLoading">
                      <spinner />
                    </div> -->
                    <ui-codemirror ui-codemirror-opts="cmOptions"
                      ng-model="app.source"
                      name="source"
                      ui-refresh="editor1">
                    </ui-codemirror>

                  </md-content>

              </md-tab>
              <md-tab label="Code Modules">

                <md-content layout="column" layout-padding>

                    <md-checkbox ng-repeat="mod in codeModules"
                      ng-model="mod.selected" flex>{{ mod.title }}</md-checkbox>

                </md-content>

              </md-tab>
              <md-tab label="Seed Structure">

                <md-content>

                  <span ng-show="appform.seedStructure.$error.validateJson"
                    class="form-error">Invalid JSON</span>

                  <ui-codemirror ui-codemirror-opts="cm2Options"
                    name="seedStructure"
                    ng-model-options="{updateOn: 'default blur'}"
                    validate-json
                    ng-model="app.seedStructure" ui-refresh="editor2">
                  </ui-codemirror>

                </md-content>

              </md-tab>
            </md-tabs>


        </div>
      </md-content>


    </form>

  </md-card-content>
  <md-card-actions>
    <md-button class="md-primary md-raised" md-ripple-size="full" ng-click="cancel()">Cancel</md-button>
    <md-button class="md-success md-raised" md-ripple-size="full" ng-click="saveapp(event)">Save</md-button>
  </md-card-actions>
</md-card>


</md-content>

www/templates/views/app-instance.html
<md-content ng-init="initInstance()">

    <!-- loading spinner -->
    <!-- <div ng-if="loading" class="loading-bg">
        <div class="loader">
          <svg class="circular">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2"
                stroke-miterlimit="10"/>
          </svg>
        </div>
        <div class="loading-text">Loading...</span></div>
    </div> -->

    <div class="feature-display"
        style="{{featureDisplayCSS}}"
        ng-show="featureDisplayContent.length > 0">
        <div ng-repeat="line in featureDisplayContent">{{ line | rawText}}</div>
    </div>


    <!-- <div id="seedDisplay">
        <md-button class="md-raised"
            ng-click="editSeed($event)"
            role="button">
            <md-icon md-font-set="material-icons">settings</md-icon>
            <span>Edit Seed</span>
        </md-button>
    </div> -->


</md-content>

www/templates/views/categories.html
<div ng-controller="CategoriesController" ng-init="init()">
	
	<!-- loading spinner -->
	<div ng-if="loading" class="loading-bg-base">
	    <div class="loader-lg">
			<svg class="circular2">
			<circle class="path" cx="125" cy="125" r="40" fill="none" stroke-width="4" 
			    stroke-miterlimit="10"/>
			</svg>
	    	<div class="loading-text">Loading...</span></div>
	    </div>
	</div>
	
	<div class="container-fluid">

		<div ng-repeat="category in categories | orderBy: 'avg_popularity': true"
			ng-repeat-end-call="onCategoryRepeatEnd($event)"
			class="col-xs-12 col-sm-6 col-md-6 col-lg-4 no-padding">

			<md-card ng-click="selectCategory(category)">
				<md-card-title>
					<md-card-title-text>
						<h3>{{ category.name }}</h3>
					</md-card-title-text>
				</md-card-title>
				<md-card-content>
					
					<div hide-xs>

						<img ng-src="/media/{{ im | thumbnail:125 }}" 
							class="nthumbnail pull-left" 
							adjust-image basewidth="80"
							ng-repeat="im in category.images | limit:imagelimit" />

					</div>
					<div hide-gt-xs>
						<img ng-src="/media/{{ im | thumbnail:125 }}" 
							class="nthumbnail pull-left" 
							adjust-image basewidth="60"
							ng-repeat="im in category.images" />
					</div>
					

				</md-card-content>
				<!-- <md-card-actions>
					<div class="text-muted pull-right">{{ category.total_popularity + category.popularity }} views</div>
				</md-card-actions> -->
			</md-card>

		</div>
		
	</div>

</div>

www/templates/views/homepage.html
<!-- <div ng-init="initHome()"> -->
    <!-- <h1>Home {{ ctrl.testvar }}</h1> -->
    HOME PAGE
<!-- </div> -->

www/templates/views/page1.html
Page1: <a ui-sref="page1.detail">Detail</a><br><br>
<div class="asset-img-2"></div>
<div class="view-change-animate" ui-view></div>

www/templates/views/paperscript.html
<div ng-controller="PaperscriptController" ng-init="init()">
	


	<!-- <canvas id="paperscript-canvas" paper style="width:100%; height: 100%;"></canvas> -->

	<div paper source="source"></div>

	<!-- <pre paper2 source="{{ source }}"></pre>
	 -->
	

</div>

www/templates/views/seedEditor.html
{{ seedlist }}
<div layout="column" ng-repeat="seed in seedlist">
    <!-- <label>{{ seed[0] }}</label>
    <input type="text" ng-model="seed[1]"
        ng-change="seedChange($event)" /> -->
    {{ seed }}
</div>

www/templates/views/toolbar.html
<div layout="row" layout-align="start center" layout-wrap>

    <div class="toolbar-title" ui-sref="app.home" flex>Apps at an Exhibition</div>

    <md-button class="md-button pull-right" flex="nogrow"
        ng-cloak ui-sref="app.login"
        ng-if="!userLoggedIn">Log in</md-button>

    <md-button class="md-button pull-right" flex="nogrow"
        ng-cloak ng-click="ctrl.logout()"
        ng-if="userLoggedIn">Log out</md-button>

</div>

<!-- <md-toolbar md-whiteframe="3" ng-cloak ng-show="false">
    <div id="top-toolbar" layout="row" layout-align="center center">

        <span class="sub-brand" ui-sref="app.home" flex="grow">
            <span flex hide-xs>Apps at an Exhibition</span>
            <span flex hide-xs>::</span>
            <span class="proposition" hide-xs>$(\forall x \in A)\space( \exists y)\space y = E(x)$</span>
            <span class="device-xs" flex hide-gt-xs>Apps at an Exhibition</span>
        </span>

        <span flex="none"> -->

            <!-- {% if user.is_authenticated %}
            <md-menu>
                <md-button ng-click="$mdOpenMenu()">
                    <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" class="avatar" />
                    {{ user.get_full_name|truncatechars:20 }}
                    <span class="caret"></span>
                </md-button>
                <md-menu-content>
                  <md-menu-item>
                      <md-button href="{% url 'profiles:show_self' %}">Profile</md-button>
                  </md-menu-item>
                  <md-menu-item>
                      <md-button href="{% url 'accounts:logout' %}">Logout</md-button>
                  </md-menu-item>
                </md-menu-content>
            </md-menu>
            {% endif %} -->

            <!-- {% if not user.is_authenticated %} -->
            <!-- <md-button class="md-button pull-right" flex
                ng-cloak ui-sref="app.login"
                ng-if="!userLoggedIn">Log in</md-button>

            <md-button class="md-button pull-right" flex
                ng-cloak ng-click="ctrl.logout()"
                ng-if="userLoggedIn">Log out</md-button> -->

            <!-- <md-button class="md-small" ng-cloak ng-href="{% url 'accounts:signup' %}" role="button">Register</md-button> -->
            <!-- {% endif %} -->
<!--
        </span>

    </div>
</md-toolbar> -->

<!-- <md-toolbar md-whiteframe="3" ng-cloak> -->

<!-- <md-fab-toolbar md-open="ctrl.menu.isOpen" count="ctrl.menu.count"
    md-direction="right" class="md-hue-1" md-scroll-shrink>

    <md-fab-trigger class="align-with-text">
      <md-button aria-label="menu" class="md-fab md-primary md-mini">
        <md-icon md-svg-src="/assets/img/icons/menu.svg"></md-icon>
      </md-button>
    </md-fab-trigger>

    <md-toolbar>

      <md-fab-actions class="md-toolbar-tools" layout="row" layout-align="end center">

        <md-button aria-label="comment" class="md-icon-button">
          <md-icon md-svg-src="img/icons/ic_comment_24px.svg"></md-icon>
        </md-button>

        <md-button aria-label="label" class="md-icon-button">
          <md-icon md-svg-src="img/icons/ic_label_24px.svg"></md-icon>
        </md-button>

        <md-button aria-label="photo" class="md-icon-button">
          <md-icon md-svg-src="img/icons/ic_photo_24px.svg"></md-icon>
        </md-button>

        <md-menu ng-if="userLoggedIn">
            <md-button ng-click="$mdOpenMenu()">
                <img src="/assets/img/profile_pics/{{ user.avatar }}" class="avatar" />

                <span class="caret"></span>
            </md-button>
            <md-menu-content>
              <md-menu-item>
                  <md-button href="">Profile</md-button>
              </md-menu-item>
              <md-menu-item>

                  <md-button class="md-button"
                      ng-cloak ui-sref="app.login"
                      ng-if="!userLoggedIn">
                      Log in
                  </md-button>

                  <md-button class="md-button"
                      ng-cloak ng-click="ctrl.logout()"
                      ng-if="userLoggedIn">
                      Log out
                  </md-button>
              </md-menu-item>
            </md-menu-content>
        </md-menu>



      </md-fab-actions>
    </md-toolbar>

</md-fab-toolbar> -->

www/templates/views/userapp.html
<paperscript-canvas source="{{$ctrl.source}}"></paperscript-canvas>

www/templates/views/view-source-dialog.html
<md-dialog aria-label="View Source" ng-init="ctrl.initialize()">

    <md-toolbar class="dialog-toolbar" md-whiteframe="2" layout-wrap>
      <div class="md-toolbar-tools">
        <h2 class="md-primary" flex="grow">Source Code</h2>
        <span flex="grow"></span>
        <md-button class="md-raised md-accent button-small"
            flex="none" role="button" ng-click="ctrl.closeDialog()">
          <md-icon md-font-set="material-icons">close</md-icon>
        </md-button>
      </div>
    </md-toolbar>

    <md-dialog-content>

      <md-content>
        <div ui-codemirror="{onLoad:ctrl.codemirrorLoaded}"
            ui-codemirror-opts="ctrl.cmOptions" class="inDialog"
            ng-model="ctrl.app.source"
            name="source">
        </div>
      </md-content>

    </md-dialog-content>

</md-dialog>